### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by zsoro2** [cometchat-pro/cometchat-pro-react-ui-kit#46]
### Describe the problem

Next.js dev mode is failing

### Error:
**_ReferenceError: window is not defined_**

### Reproduction

Use these dependencies:
```
  "dependencies": {
    "@cometchat-pro/chat": "^2.2.1",
    "next": "^10.0.0",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",

```

**Comment by anantgarg** [comment]
@zsoro2 We are working on a fix, but here is a temporary workaround:

https://paper.dropbox.com/doc/Next.js-Support-experimental--BHOqpQIljGW3NuuZd9wvXSr2Ag-E66xhsRRboOkapyVIXvc3

**Comment by paarthsabharwal** [comment]
Hi @zsoro2 , We will be working on this shortly. We will circle back with updates soon.

**Comment by priyadarshininadar** [comment]
Hi @zsoro2 ,
Our React UI Kit is now compatible with Next.js. Please follow this documentation for integration: [Next js integration](https://prodocs.cometchat.com/docs/integration-with-nextjs)
