### ISSUE TITLE
Why do we need to clone this repository?

### ISSUE THREAD

**Issue by jahirfiquitiva** [cometchat-pro/cometchat-pro-react-ui-kit#51]
Why don't you publish this as you do with the SDK and make it easier for developers to implement?

**Comment by anantgarg** [comment]
@jahirfiquitiva We believe that adding our UI Kit into your application allows you to customize the UI exactly as per your needs (as we provide the complete source code). Although it may take a little more effort on your end, the flexibility that you can achieve will make it worth the effort.

**Comment by carmona** [comment]
I've come to ask the same question, and @anantgarg I believe you could still provide the source code through a NPM package and have it be customizable through CSS.
@jahirfiquitiva may I ask if/how you managed to work around this?

**Comment by jahirfiquitiva** [comment]
@carmona We actually moved to a [different sdk](https://getstream.io/chat/)

**Comment by anantgarg** [comment]
@carmona We have launched new UI Kits (currently in beta) which are distributed via package managers:  https://www.cometchat.com/blog/next-gen-ui-kits

React will be launching shortly as well.

**Comment by anantgarg** [comment]
@carmona Our new React UI Kit is now available in beta: https://www.cometchat.com/docs/react-uikit-beta/overview
