### ISSUE TITLE
importSource cannot be set when runtime is classic.

### ISSUE THREAD

**Issue by jahirfiquitiva** [cometchat-pro/cometchat-pro-react-ui-kit#52]
### Describe the problem

I'm running this with a NextJS project

### What was the expected behavior?

App compiling and rendering as expected

### Environment

> Please provide the following:

- **Version used:** 3.0.0-beta1

**Comment by jahirfiquitiva** [comment]
Same thing is happening with v 2.3.2

**Comment by jahirfiquitiva** [comment]
I'm using NextJS 10.2.0 and react 17.0.2

**Comment by priyadarshininadar** [comment]
This has fixed in [https://github.com/cometchat-pro/cometchat-pro-react-ui-kit/releases/tag/v2.3.5-1](https://github.com/cometchat-pro/cometchat-pro-react-ui-kit/releases/tag/v2.3.5-1)
