### ISSUE TITLE
Clone and import new repo got error module parse

### ISSUE THREAD

**Issue by mrtk0y** [cometchat-pro/cometchat-pro-react-ui-kit#60]
### Describe the problem
Clone cometchat-pro-react-ui-kit repo
and import CometChatUI got error
![image](https://user-images.githubusercontent.com/37510824/120957045-22969500-c77f-11eb-81c0-a4942db7dcc1.png)

### What was the expected behavior?
Import and use as normal

### Reproduction
 - Step 1: git clone https://github.com/cometchat-pro/cometchat-pro-react-ui-kit.git
 - Step 2: and Import as docs
![image](https://user-images.githubusercontent.com/37510824/120957443-e0ba1e80-c77f-11eb-815b-a37fb3991e1a.png)

### Environment
 - @cometchat-pro/chat": "2.1.4"
 - "next": "^10.0.0",
 - "react": "^17.0.1",

**Comment by mrtk0y** [comment]
by comment all the place import audio, I manage to make it run 
![image](https://user-images.githubusercontent.com/37510824/120958372-ced97b00-c781-11eb-8aa5-d6ba74e73030.png)

**Comment by priyadarshininadar** [comment]
Hi @mrtk0y ,
you can toggle off sound for incoming/outgoing messages by using this method: UIKitSettings.setEnableSoundForMessages(false). Please refer to this link for more such customization: [https://prodocs.cometchat.com/docs/react-ui-kit-customize](https://prodocs.cometchat.com/docs/react-ui-kit-customize)

**Comment by mrtk0y** [comment]
> Hi @mrtk0y ,
> you can toggle off sound for incoming/outgoing messages by using this method: UIKitSettings.setEnableSoundForMessages(false). Please refer to this link for more such customization: https://prodocs.cometchat.com/docs/react-ui-kit-customize

Ah yes, I read the docs, but I don't know where to add "UIKitSettings.setEnableSoundForMessages"
I'm not really familiar with class style
I tried 
```static setEnableSoundForMessages = false ```
in UIKitSettings file but no use

**Comment by priyadarshininadar** [comment]
You can use the method before importing any of the UI Kit components.
If you are trying to integrate the UI Kit with a Next.js project, please make sure you follow this documentation: [Next js integration](https://prodocs.cometchat.com/docs/integration-with-nextjs)
