### ISSUE TITLE
Got error type from using CometChatMessages

### ISSUE THREAD

**Issue by mrtk0y** [cometchat-pro/cometchat-pro-react-ui-kit#61]
### Describe the problem
Using CometChatMessages got type error
![image](https://user-images.githubusercontent.com/37510824/120958951-f0873200-c782-11eb-9311-a8a6384a232f.png)

### Reproduction

- Step 1: Clone comet pro UI kit
- Step 2: Comment all the audio cause https://github.com/cometchat-pro/cometchat-pro-react-ui-kit/issues/60
- Step 3: using <CometChatMessages chatWithGroup={groupId} />
- Step 4: error

code: ![image](https://user-images.githubusercontent.com/37510824/120959304-a5b9ea00-c783-11eb-9d23-fb06f7457cd7.png)

### Environment
 - @cometchat-pro/chat": "2.1.4"
 - "next": "^10.0.0",
 - "react": "^17.0.1",

**Comment by japaveh** [comment]
I get the same issue, but don't think it is related to the sound

![image](https://user-images.githubusercontent.com/1028237/124152788-1c50bb80-da94-11eb-812e-1904213e6cbd.png)

**Comment by priyadarshininadar** [comment]
> I get the same issue, but don't think it is related to the sound
> 
> ![image](https://user-images.githubusercontent.com/1028237/124152788-1c50bb80-da94-11eb-812e-1904213e6cbd.png)

This is fixed for v2 app in https://github.com/cometchat-pro/cometchat-pro-react-ui-kit/releases/tag/v2.3.6-3

**Comment by japaveh** [comment]
Great, it works, Thanks
Any chance that this fix is also pushed into the v3 branch?
