### ISSUE TITLE
Unable to compile UI Kit. Compiler error, no-unused-expressions

### ISSUE THREAD

**Issue by RajarshiPrattipati** [cometchat-pro/cometchat-pro-react-ui-kit#84]
### Describe the problem

Tried to integrate the CometChat UI.

Failed to compile.

(undefined) ./src/CometChatWorkspace/src/components/Messages/CometChatMessageList/index.js
  Line 111:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 121:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 143:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

### Reproduction

- Step 1.. Followed Steps 1-3 in the README
- Step 2.. Ran npm start
- ...

### Environment

 "engines": {
    "node": "10"
  },

  "dependencies": {
    "@babel/polyfill": "^7.7.0",
    "@babel/runtime": "^7.7.7",
    "@firebase/app": "^0.5.1",
    "@firebase/auth": "^0.13.4",
    "@material-ui/core": "^4.8.3",
    "@material-ui/icons": "^4.5.1",
    "body-parser": "^1.19.0",
    "clsx": "^1.0.4",
    "cookie": "^0.4.0",
    "cookie-parser": "^1.4.4",
    "dataloader": "^2.0.0",
    "dotenv": "^8.2.0",
    "ejs": "^3.0.1",
    "express": "^4.17.1",
    "express-graphql": "^0.9.0",
    "firebase-admin": "^8.9.0",
    "firebase-functions": "^3.3.0",
    "got": "^10.2.2",
    "graphql": "^14.5.8",
    "graphql-relay": "^0.6.0",
    "history": "^4.10.1",
    "hoist-non-react-statics": "^3.3.1",
    "idx": "^2.5.6",
    "jsonwebtoken": "^8.5.1",
    "jwt-passport": "^0.0.5",
    "knex": "^0.20.7",
    "load-script": "^1.0.0",
    "lodash": "^4.17.15",
    "moment-timezone": "^0.5.27",
    "passport": "^0.4.1",
    "passport-facebook": "^3.0.0",
    "passport-google-oauth20": "^2.0.0",
    "pg": "^7.17.0",
    "prop-types": "^15.7.2",
    "query-string": "^6.9.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-relay": "^8.0.0",
    "recompose": "^0.30.0",
    "relay-runtime": "^8.0.0",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.8",
    "serialize-javascript": "^2.1.2",
    "slugify": "^1.3.6",
    "universal-router": "^8.3.0",
    "uuid": "^3.3.3",
    "validator": "^12.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/register": "^7.7.7",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-relay": "^8.0.0",
    "chai": "^4.2.0",
    "eslint-config-prettier": "^6.9.0",
    "eslint-plugin-prettier": "^3.1.2",
    "husky": "^4.0.4",
    "lint-staged": "^9.5.0",
    "minimist": "^1.2.0",
    "prettier": "^1.19.1",
    "raw-loader": "^4.0.0",
    "react-app-tools": "^3.1.0-preview.7",
    "relay-compiler": "^8.0.0"
  },

**Comment by proveshapyne** [comment]
Hey @RajarshiPrattipati,

We have responded to you regarding this issue via email. I would appreciate it if we could stay connected there, and thus, I am closing out this ticket.
Thank you.

Regards,
Provesha

**Comment by shkhaider2015** [comment]
I am facing a similar issue.
